#!/bin/bash

# Set's SDK repos to latest version for Mer Core and SDK

# Default to getting latest stable release (don't distinguish between
# Mer/SDK for now)
PRE="latest"

usage()
{
    cat <<EOF
    usage: $1 

     Update the zypper repos to point to the latest, next or specified
     Mer / SDK releases

     By default checks
        http://releases.merproject.org/releases/latest-release
        http://repo.pub.meego.com/releases/Mer-Tools/latest-release

     --next : Check for the 'next' release instead of 'latest'

     --core <release> : Use Mer Core <release> instead of checking for latest/next
                        eg: --core 0.20120517.1
     --sdk  <release> : Use SDK <release> instead of checking for latest/next
                        eg: --sdk 0.5.1
EOF
    return 0
}

while [[ $1 ]] ; do
    case $1 in
	--core ) CORE=$2 ; shift ;;
	--sdk ) SDK=$2 ; shift ;;
	--next ) PRE="next";;

	* ) usage; exit 1 ;;
    esac
    shift
done

[[ $CORE ]] || CORE=$(curl -Ss http://releases.merproject.org/releases/$PRE-release)
[[ $SDK ]] || SDK=$(curl -Ss http://repo.pub.meego.com/releases/Mer-Tools/$PRE-release)

backup() {
    [ -f $1 ] && mv $1 $1$2
}

backup /etc/zypp/repos.d/mer-tools-i486.repo -pre-$CORE

cat <<EOF > /etc/zypp/repos.d/mer-tools-i486.repo
[mer-tools-i486]
name=mer-tools-i486
failovermethod=priority
baseurl=http://repo.pub.meego.com/releases/Mer-Tools/$SDK/builds/i486/packages/
gpgcheck=0
enabled=1

[mer-tools-i486-debuginfo]
name=mer-tools-i486-debuginfo
failovermethod=priority
baseurl=http://repo.pub.meego.com/releases/Mer-Tools/$SDK/builds/i486/debug
gpgcheck=0
enabled=0
EOF

backup /etc/zypp/repos.d/mer-core.repo -pre-$CORE
cat <<EOF > /etc/zypp/repos.d/mer-core.repo 
[mer-core]
name=mer-core
failovermethod=priority
baseurl=http://releases.merproject.org/releases/$CORE/builds/i486/packages
gpgcheck=0
enabled=1

[mer-core-debuginfo]
name=mer-core-debuginfo
failovermethod=priority
baseurl=http://releases.merproject.org/releases/$CORE/builds/i486/debug
gpgcheck=0
enabled=0
EOF

backup /etc/zypp/repos.d/mer-cross-tools.repo -pre-$CORE
cat <<EOF > /etc/zypp/repos.d/mer-cross-tools.repo
[mer-cross-tools]
name=mer-cross-tools
failovermethod=priority
baseurl=http://releases.merproject.org/releases/$CORE/builds/i486/cross/
gpgcheck=0
enabled=1

[mer-cross-tools-debuginfo]
name=mer-cross-tools-debuginfo
failovermethod=priority
baseurl=http://releases.merproject.org/releases/$CORE/builds/i486/debug
gpgcheck=0
enabled=0
EOF

[ -f /etc/zypp/repos.d/mer-tools-testing-i486.repo ] && {
    cat <<EOF
You have a repo for the Mer:Tools:Testing project.
This is very volatile and could lead to breakage in your SDK.
You should remove it unless you know you need it. Run:
   sudo rm /etc/zypp/repos.d/mer-tools-testing-i486.repo
EOF
}

cat <<EOF
Now run:
  sudo zypper ref
  sudo zypper up
EOF