#!/bin/bash
#
# Copyright (C) 2022 Jolla Ltd.
# Contact: http://jolla.com/
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# - Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -o nounset

host_is_windows() [[ -e /dev/fuse ]]
inside_virtualbox() [[ $(systemd-detect-virt) == oracle ]]

extra_args=()

# Both vboxsf and dynexecfs have some impact on file stat data and that
# would confuse git. The less obious being subsecond part stripped from
# times and inode numbers not matching those on host at least. Some
# differences may be observed even under Docker on Linux where the filesystem
# is simply bind-mounted. At least 'stat' may report different device ID in
# that case.
if inside_virtualbox \
        || host_is_windows && ! [[ -e /etc/mersdk/share/workspace1.no-dynexec ]]; then
    extra_args+=(-c core.fileMode=false)
fi
extra_args+=(-c core.checkStat=minimal)

command=${0##*/}
path=${0%/*}
real=$(PATH=${PATH/$path:/} which "$command")
if [[ ! $real || $real == "$0" ]]; then
    echo "$0: Cannot find real $command" >&2
    exit 1
fi

exec "$real" "${extra_args[@]}" "$@"
