#!/bin/sh
# Transitional mb2 wrapper script.
# This will go away at some point. Please use mb2 directly.

cat >/dev/stderr <<EOF

  'mb' is obsolete, please use 'mb2'

  Some common commands that replace your mb usage:

    mb2 -t jolla-arm build ....... Build with the "jolla-arm" sb2 target
    mb2 -t jolla-i486 build ...... Build with the "jolla-i486" sb2 target
    mb2 -t jolla-arm -s rpm/foo.spec build ... Specify .spec file to use

  Note that mb2 builds the source tree locally and puts RPMs into "./RPMS/".

EOF
