#!/bin/sh
#
# Resize root FS to fully use the available space on the device
#
# Copyright (C) 2019 Jolla Ltd.
# Contact: Martin Kampas <martin.kampas@jollamobile.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# - Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -o errexit

devsize()
{
    blockdev --getsz /dev/sda
}

partsize()
{
    local dump=
    dump=$(sfdisk --dump /dev/sda)
    sed -n 's,^/dev/sda1 : .*size=[[:space:]]*\([0-9]\+\).*,\1,p' <<<"$dump"
}

expandpart()
{
    sfdisk --force -N 1 /dev/sda <<<", +"
    newsize=$(partsize)
    resizepart /dev/sda 1 "$newsize"
    resize2fs /dev/sda1
}

devsize=$(devsize)
partsize=$(partsize)
tolerance=1024
# Due to alignment etc. the partition will always be a bit smaller
[ $((devsize - partsize)) -lt $tolerance ] || expandpart
