#!/bin/bash

if [[ -e /resize_root_fs ]]; then
   resize2fs /dev/sda1
   rm /resize_root_fs	
   exit
fi

pre=$(mktemp)
post=$(mktemp)

# Store partition table
dd if=/dev/sda bs=1k count=1 of=$pre  > /dev/null 2>&1

grep -v "^#" << RESIZE | fdisk /dev/sda > /dev/null 2>&1
# Taken from http://www.mail-archive.com/devel@lists.sailfishos.org/msg00273.html
# Delete partition 1, type:
d
# Recreate using full size
n
p
1


# make it bootable
a
1
# Now we use the 'expert menu' to set the partition start to 1, type:
x
b
1
1
r
# Write and exit, type
w
RESIZE

# Store partition table
dd if=/dev/sda bs=1k count=1 of=$post  > /dev/null 2>&1

if ! diff -q $pre $post >/dev/null 2>&1; then
   echo "Partition table changed, rebooting"
   touch /resize_root_fs
   rm $pre $post
   reboot
fi
rm $pre $post
