#!/bin/bash

TIMEOUT=10
DEV=eth0

echo 3 > /proc/sys/kernel/printk

cnt=0
echo waiting for IP
while (( $cnt < $TIMEOUT )); do
    IP=$(/sbin/ip -4 addr show dev $DEV scope global | grep "inet"  | cut -f6 -d' ' | cut -f1 -d'/' )
    [[ $IP ]] && break
    sleep 1;
    (( cnt++ ))
    IP="Unknown"
done

/usr/bin/chvt 1
/usr/bin/setterm -powersave off -blank 0
/usr/bin/clear

# This sets the font colour
if [ -e /etc/sysconfig/splashfontcol ]; then
   # put 2 echo commands in here to customise as vendor
   . /etc/sysconfig/splashfontcol
else
# last 6 digits of the echos are RRGGBB
  /bin/echo -en '\033]P7B1BFDB' # fg
  /bin/echo -en '\033]P0011130' # bg
fi

/usr/bin/tput cup 25 0
/usr/bin/ply-image

cat << EOF
  Welcome to the Mer build machine.

  Use "right-ctrl F2" to get a login prompt.
 
  Your VM SDK IP address is:  $IP

  Note that if you have configured VirtualBox to use NAT for this VM you
  should use
    ssh -p 2222 root@localhost

  Mounting shared folders....
EOF

fail=
if VBoxControl -nologo sharedfolder list | grep ' home$' > /dev/null 2>&1 ; then
    mount -tvboxsf -o"rw,exec,uid=1001,gid=1001,dev,ttl=200,fmode=700,dmode=700"  home /home/mersdk || fail=1
else
    echo '  Failed to mount shared folder "home"'
    fail=1
fi
if VBoxControl -nologo sharedfolder list | grep ' ssh$' > /dev/null 2>&1 ; then
    mount -tvboxsf -o"rw,exec,uid=0,gid=0,dev,fmode=555,dmode=555"  ssh /etc/ssh/authorized_keys || fail=1
else
    echo '  Failed to mount shared folder "ssh" - ssh will not work, use console login as root'
    fail=1
fi
if VBoxControl -nologo sharedfolder list | grep ' targets$' > /dev/null 2>&1 ; then
    mount -tvboxsf -o"rw,exec,uid=1001,gid=1001,dev,ttl=200"  targets /host_targets || fail=1
else
    echo '  Failed to mount shared folder "targets"'
    fail=1
fi

if [[ $fail ]]; then
    VBoxControl -nologo sharedfolder list
    echo "  Please see https://wiki.merproject.org/wiki/Platform_SDK_on_VirtualBox"
    echo "  for instructions on setting up"
else
    echo "  mounted home and targets succesfully"
fi

/bin/echo -en '\033]R'


