#!/usr/bin/python
import sys
import lxml.etree as et
import argparse
import os
import subprocess

def get_value(root, var):
    try:
        count = [el for el in root.findall(".//variable") if el.text == var]
        return count[0].getparent().find("value").text
    except Exception as e:
        print "Could not find '%s' in targets xml (%s)" % (var, e)
        sys.exit(1)

def set_value(root, var, val):
    try:
        count = [el for el in root.findall(".//variable") if el.text == var]
        count[0].getparent().find("value").text = val
    except Exception as e:
        print "Could not set '%s' in targets xml (%s)" % (var, e)
        sys.exit(1)

def find_target_by_name(root, name):
    try:
        for el in root.findall(".//value[@key='MerTarget.Name']"):
            if el.text == name:
                return el.getparent().getparent()
    except Exception as e:
        print "Error lookin for target named '%s' in targets xml (%s)" % (name, e)
        sys.exit(1)

def assert_valid_sb2_name(name):
    if not os.path.isdir(os.path.expanduser("~/.scratchbox2/%s" % name)):
        raise Exception("%s is not a valid scratchbox name" % name)

def sb2_command(sb2, *args):
    data = subprocess.check_output(["sb2", "-t", sb2] + list(args))
    if data:
        return data
    raise Exception("'%s' returned no data" % " ".join(args))
    
def main(args):
    name = args.name
    # http://lxml.de/FAQ.html#why-doesn-t-the-pretty-print-option-reformat-my-xml-output
    parser = et.XMLParser(remove_blank_text=True)
    tree = et.parse(args.target_xml, parser)
    root = tree.getroot()

    assert_valid_sb2_name(name)
    
    if int(get_value(root, "MerTarget.Version")) != 2:
        raise Exception("Only version 2 of MerTarget XML is supported")

    num_t = int(get_value(root, "MerTarget.Count"))

    data = et.Element("data")

    # See if there is a target using this name already
    existing = find_target_by_name(root, name)
    if et.iselement(existing):
        # if so then what number is it before we remove it
        t_index = existing.find("variable").text.split(".")[1]
        root[root.index(existing)] = data
    else:
        root.insert(num_t, data)
        t_index = num_t
        num_t += 1

    # Now build the target info
    var = et.SubElement(data, "variable")
    var.text = "MerTarget.%s" % t_index
    vm = et.SubElement(data, "valuemap", type="QVariantMap")
    et.SubElement(vm, "value", type="QString", key="MerTarget.Name").text = name
    et.SubElement(vm, "value", type="QString", key="MerTarget.GccMachineDump"
                  ).text = sb2_command(name, "gcc", "-dumpmachine")
    et.SubElement(vm, "value", type="QString", key="MerTarget.QmakeQuery"
                  ).text = sb2_command(name, "qmake", "-query")

    set_value(root, "MerTarget.Count", "%s" % (num_t))

    with open(args.target_xml, 'w') as f:
        f.write(et.tostring(root, pretty_print=True))
    
                                         
parser = argparse.ArgumentParser(description='Updates QtCreator Target XML file with a new Mer Target')

parser.add_argument('--name', required=True,
                    help="Name of sdk target")
parser.add_argument('--target-xml', required=True,
                    help="The QtCreator Targets xml file")

args = parser.parse_args()

main(args)
